"""empty message

Revision ID: 9c4fa4172bf3
Revises: a6ab4e00a915
Create Date: 2026-07-15 08:21:49.672890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4fa4172bf3'
down_revision = 'a6ab4e00a915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stored_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('submission_file')
        batch_op.drop_column('submission_original_name')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('pdf_file')
        batch_op.drop_column('pdf_original_name')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pdf_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('assignment_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_original_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('submission_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('stored_filename')

    # ### end Alembic commands ###
